[2024-05-06T03:38:56.972+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: diabetes_prediction_2.train_model scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-05-06T03:38:57.127+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: diabetes_prediction_2.train_model scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-05-06T03:38:57.128+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-05-06T03:38:57.391+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): train_model> on 2024-05-01 00:00:00+00:00
[2024-05-06T03:38:57.472+0000] {standard_task_runner.py:57} INFO - Started process 352 to run task
[2024-05-06T03:38:57.567+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'diabetes_prediction_2', 'train_model', 'scheduled__2024-05-01T00:00:00+00:00', '--job-id', '276', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmp9o5xe6gu']
[2024-05-06T03:38:57.582+0000] {standard_task_runner.py:85} INFO - Job 276: Subtask train_model
[2024-05-06T03:38:57.971+0000] {task_command.py:410} INFO - Running <TaskInstance: diabetes_prediction_2.train_model scheduled__2024-05-01T00:00:00+00:00 [running]> on host 18590e1a4d2d
[2024-05-06T03:38:58.683+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='diabetes_prediction_2' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-01T00:00:00+00:00'
[2024-05-06T03:39:04.063+0000] {logging_mixin.py:149} WARNING - 2024/05/06 03:39:04 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-05-06T03:57:10.071+0000] {local_task_job_runner.py:299} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-05-06T03:57:10.101+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 352. PIDs of all processes in the group: [352]
[2024-05-06T03:57:10.102+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 352
[2024-05-06T03:57:10.261+0000] {taskinstance.py:1540} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-06T03:58:10.116+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=352, name='airflow task ru', status='running', started='03:38:57') did not respond to SIGTERM. Trying SIGKILL
[2024-05-06T03:58:10.117+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGKILL to group 352
[2024-05-06T03:58:10.499+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=352, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='03:38:57') (352) terminated with exit code Negsignal.SIGKILL
[2024-05-06T03:58:10.500+0000] {standard_task_runner.py:174} ERROR - Job 276 was killed before it finished (likely due to running out of memory)
